name: Test Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test if this works
      run: run: |
        version="$(grep -o -m 1 'RADARR_VERSION=.*' Dockerfile | awk -F '=' '{print $2}')"
        echo $version
